tools:
    shell:
        allow:
            - find *
            - head *
            - ls *
            - xargs *
            - grep *
            - cd *
            - .venv/bin/python *
            - tail *
